# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryMapKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='字母编码')),
                ('frequency', models.IntegerField(default=0, verbose_name='出现次数')),
            ],
        ),
        migrations.CreateModel(
            name='SignificantValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='联想词汇')),
                ('remark', models.CharField(max_length=512, verbose_name='描述')),
                ('related_type', models.CharField(choices=[('acronym', '拼写缩写'), ('comics', '动漫'), ('game', '游戏'), ('Internet', '网络用语'), ('dialect', '方言俗语'), ('personal', '个人专用')], default='acronym', max_length=30, verbose_name='联想类型')),
                ('images', models.CharField(blank=True, max_length=512, null=True)),
                ('supported', models.IntegerField(default=0, verbose_name='支持人数')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codemap.MemoryMapKey')),
            ],
        ),
    ]
